//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/space leader controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Spaceleadercontrols: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Spaceleadercontrols()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""space leader controls"",
    ""maps"": [
        {
            ""name"": ""rightXrController"",
            ""id"": ""1a2559da-1c81-40d6-8ce1-e570b29b88ca"",
            ""actions"": [
                {
                    ""name"": ""speed"",
                    ""type"": ""Value"",
                    ""id"": ""9333337c-22ab-4fab-8f66-d7a15e19e73d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rotation"",
                    ""type"": ""Value"",
                    ""id"": ""093f3ec1-46b2-4a62-b006-a0c0fe786d2b"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""grip"",
                    ""type"": ""Button"",
                    ""id"": ""5b677398-025f-4132-98dd-44172171b551"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c45192bd-82ad-4cd8-b8e1-8015cb85f599"",
                    ""path"": ""<XRController>{RightHand}/{Trigger}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""471bfdfc-9d4a-418b-9bbc-387d918a67b8"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfca484f-e261-4e3d-bb4c-8e63258e43c1"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // rightXrController
        m_rightXrController = asset.FindActionMap("rightXrController", throwIfNotFound: true);
        m_rightXrController_speed = m_rightXrController.FindAction("speed", throwIfNotFound: true);
        m_rightXrController_rotation = m_rightXrController.FindAction("rotation", throwIfNotFound: true);
        m_rightXrController_grip = m_rightXrController.FindAction("grip", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // rightXrController
    private readonly InputActionMap m_rightXrController;
    private List<IRightXrControllerActions> m_RightXrControllerActionsCallbackInterfaces = new List<IRightXrControllerActions>();
    private readonly InputAction m_rightXrController_speed;
    private readonly InputAction m_rightXrController_rotation;
    private readonly InputAction m_rightXrController_grip;
    public struct RightXrControllerActions
    {
        private @Spaceleadercontrols m_Wrapper;
        public RightXrControllerActions(@Spaceleadercontrols wrapper) { m_Wrapper = wrapper; }
        public InputAction @speed => m_Wrapper.m_rightXrController_speed;
        public InputAction @rotation => m_Wrapper.m_rightXrController_rotation;
        public InputAction @grip => m_Wrapper.m_rightXrController_grip;
        public InputActionMap Get() { return m_Wrapper.m_rightXrController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightXrControllerActions set) { return set.Get(); }
        public void AddCallbacks(IRightXrControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_RightXrControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightXrControllerActionsCallbackInterfaces.Add(instance);
            @speed.started += instance.OnSpeed;
            @speed.performed += instance.OnSpeed;
            @speed.canceled += instance.OnSpeed;
            @rotation.started += instance.OnRotation;
            @rotation.performed += instance.OnRotation;
            @rotation.canceled += instance.OnRotation;
            @grip.started += instance.OnGrip;
            @grip.performed += instance.OnGrip;
            @grip.canceled += instance.OnGrip;
        }

        private void UnregisterCallbacks(IRightXrControllerActions instance)
        {
            @speed.started -= instance.OnSpeed;
            @speed.performed -= instance.OnSpeed;
            @speed.canceled -= instance.OnSpeed;
            @rotation.started -= instance.OnRotation;
            @rotation.performed -= instance.OnRotation;
            @rotation.canceled -= instance.OnRotation;
            @grip.started -= instance.OnGrip;
            @grip.performed -= instance.OnGrip;
            @grip.canceled -= instance.OnGrip;
        }

        public void RemoveCallbacks(IRightXrControllerActions instance)
        {
            if (m_Wrapper.m_RightXrControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightXrControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_RightXrControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightXrControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightXrControllerActions @rightXrController => new RightXrControllerActions(this);
    public interface IRightXrControllerActions
    {
        void OnSpeed(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnGrip(InputAction.CallbackContext context);
    }
}
